// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNRESKXOCRMOcEamjGg_djIG6htTIkMaU',
    appId: '1:955700338638:web:e30999014068b61f81559f',
    messagingSenderId: '955700338638',
    projectId: 'green-drop-e7b59',
    authDomain: 'green-drop-e7b59.firebaseapp.com',
    storageBucket: 'green-drop-e7b59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefEqHVZfMYcjy-y6YktZIsdr8khCogO0',
    appId: '1:955700338638:android:ff961a531db3628081559f',
    messagingSenderId: '955700338638',
    projectId: 'green-drop-e7b59',
    storageBucket: 'green-drop-e7b59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi6vmv8R-ck7y9u1_yPIBp3gyKPmFly2Y',
    appId: '1:955700338638:ios:72a1179acb827cc281559f',
    messagingSenderId: '955700338638',
    projectId: 'green-drop-e7b59',
    storageBucket: 'green-drop-e7b59.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi6vmv8R-ck7y9u1_yPIBp3gyKPmFly2Y',
    appId: '1:955700338638:ios:72a1179acb827cc281559f',
    messagingSenderId: '955700338638',
    projectId: 'green-drop-e7b59',
    storageBucket: 'green-drop-e7b59.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNRESKXOCRMOcEamjGg_djIG6htTIkMaU',
    appId: '1:955700338638:web:b63ca47fba46a0ef81559f',
    messagingSenderId: '955700338638',
    projectId: 'green-drop-e7b59',
    authDomain: 'green-drop-e7b59.firebaseapp.com',
    storageBucket: 'green-drop-e7b59.firebasestorage.app',
  );
}
